# -*- coding: utf-8 -*-
__author__ = 'liaoben'


CASE = {
    #clue
    'AddNinePicsTest.testSendNinePics':['2-4399','2-4811'],
    #search
    'SearchBackTest.testSearchBack':'1-826',
    'SearchBasicTest.testArticleSearch':'1-834',
    'SearchBasicTest.testVideoSearch':'',
    'SearchBasicTest.testAudioSearch':'',
    'SearchBasicTest.testExtSearch':'1-833',
    'SearchBasicTest.testPhotoSearch':'1-832',
    'SearchBasicTest.testTargeturlSearch':'1-833',
    'SearchBasicTest.testZhuantiSearch':'1-3211',
    'SearchBasicTest.testNewspaper':'1-835',
    'SearchBasicTest.testHead':'1-836',
    'SearchBasicTest.testZhuanlanSearch':'1-3211',
    'SearchBasicTest.testFocus':'1-830',
    'HeadPicInSearchTest.testHeadPic':'1-837',
    'HotwordsTest.testHotwords':'1-824',
    'NonResultTest.testNonResult':'1-850',
    'SearchInDiffChnlTest.testSearchInDiffChnl':'1-822',
    'SearchCancelTest.testSearchCancel':'1-826',
    'SearchSlideTest.testSearchSlide':'1-845',
    'SearchStyleTest.testNormalArticle':'1-829',
    'SearchStyleTest.testSinglePicArticle':'1-829',
    'SearchStyleTest.testBigPicArticle':'1-829',
    'SearchStyleTest.testThreePicArticle':'1-829',
    'SearchStyleTest.testFlagArticle':'',
    'SearchStyleTest.testVideoArticle':'1-1737',
    'SearchTimeTest.testSearchTime':'1-831',
    'SearchTwiceTest.testSearch':'1-840',
    'ErrArticleSearchTest.testErrSearch':'1-848',

    #audio
    'AppQuitTest.testQuit':'2-3260',
    'AppQuitTest.testNotificationPause':'',
    'AppQuitTest.testBackLocation':'2-3261',
    'ArticleAudioTest.testDestroy':'2-3229',
    'ArticleAudioTest.testPlayerLocation':'2-3231',
    'ArticleAudioTest.testBack':'2-3244',
    'ArticleAudioTest.testPauseBack':'2-3246',
    'AudioCommentListTest.test':'2-3211',
    'AudioDestroyTest.test':'2-3209',
    'AudioDestroyTest.testNotification':'2-3258',
    'BackgroundTest.testSwitch':'2-3195',
    'BackgroundTest.testAudioHome':'2-3195',
    'BackgroundTest.testBack':'2-3207',
    'BackTest.test':'',
    'ElementsTest.test':'2-3197',
    'MultiAudioPlayTest.test':'2-3219',
    'NotificationSwipeTest.test':'2-3263',
    'NotificationCloseTest.test':'2-3264',
    'NotificationTest.test':'2-3255',
    'NotificationTest.testFinish':'2-3266',
    'NotificationTest.testCreate':'2-3257',
    'NotificationTest.testJump':'2-3267',
    'NotificationTest.testJumpNormalArticle':'2-3269',
    'PlayCountTest.test':'2-3175',
    'PlayPauseTest.test':'2-3180',
    'PlayPauseTest.testAutoStart':'2-3215',
    'ProgressTest.test':'2-3182',

    #push
    'ArticlePushTest.test':'2-4040',
    'AudioPushTest.testAudio':'2-4053',
    'AudioPushTest.testArticleAudio':'',
    'AudioPushTest.testPlayAudio':'2-4055',
    'AudioPushTest.testPlayAudioArticle':'2-4056',
    'DefaultTest.test':'2-4036',
    'JpushBasicTest.test':'2-4037',
    'MultiPushTest.test':'2-4045',
    'MultiPushTest.testPushMsg':'2-4045',
    'NotificationClearTest.test':'',
    'PushBackTest.testBasic':'2-4041',
    'PushBackTest.testStart':'2-4042',
    'PushBackTest.testBack':'2-4046',
    'PushBackTest.testAppStart':'2-4039',
    'UnsupportTest.testNonContent':'2-4054',
    'UnsupportTest.testContent':'2-4054',
    'VideoPushTest.testLive':'2-4054',
    'VideoPushTest.testVideo':'2-4052',

    #upgrade
    'ForceUpdateTest.test':'2-4070',
    'IgnoreTest.test':'2-4071',
    'NoUpdateTest.test':'2-4064',
    'UpdateBasicTest.test':'2-4063',
    'UpdateBasicTest.testElements':'2-4065',
    'UpdateBasicTest.testRemind':'2-4068',
    'UpdateManualTest.test':'2-4066',
    'UpdateMethodTest.test':'2-4067',

    #comment
    'NoneCommentTest.testArticleComment':'2-2902',
    'CommentForbiddenTest.testVideoComment':'2-2971',
    'CommentForbiddenTest.testArticleComment':'2-2967',
    'CommentForbiddenTest.testPhotoComment':'2-2970',
    'CommentForbiddenTest.testExtComment':'2-3541',
    'CommentForbiddenTest.testAudioComment':'2-2973',
    'AmazingCommentTest.testNonExsit':'2-2951',
    'AmazingCommentTest.testExsit':'',
    'ArticleAmazingTest.testExsit':'2-2958',
    'CommentBasicTest.testVideoComment':'2-2910',
    'CommentBasicTest.testArticleComment':'2-2935',
    'CommentBasicTest.testPhotoComment':'2-2910',
    'CommentBasicTest.testExtComment':'2-2910',
    'CommentBasicTest.testAudioComment':'2-2910',
    'CommentDiggCountTest.test':'',
    'CommentDiggtTest.testVideoComment':'2-2943',
    'CommentDiggtTest.testArticleComment':'2-2943',
    'CommentDiggtTest.testPhotoComment':'2-2943',
    'CommentDiggtTest.testExtComment':'2-2943',
    'CommentDiggtTest.testAudioComment':'2-2943',
    'CommentReplyTest.testArticleComment':'2-2933',
    'CommentSlideTest.test':'2-2954',
    'CommentTimeTest.testArticleComment':'2-2924',
    'ReplyCountTest.testCommentArticle':'',
    'ReplyCountTest.testCommentPhoto':'',
    'ReplyCountTest.testCommentAudio':'',




}